"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['aquarium.py']
DATA_FILES = [('', ['img'])]
OPTIONS = {
            'argv_emulation': True,
            'packages': ['tkinter'],
            'iconfile': 'img/icon.icns',
             }

setup(
    app=APP,
    name='aquarium',
    author='Jan Vicha',
    url='https://github.com/vichi99',
    version='0.1',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
